# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [1]:
# a)
a = 2.0 + 3.0 / 5.0
print(a)
# b)
b = (a + 10.2) - 5.0 * 2.0
print(b)
# c)
c = a / b + 33.8
print(c)
# d)
d = a / (b + c)
print(d)
# e)
e = d * 2
print(e)

2.6
2.799999999999999
34.72857142857143
0.0692805481537876
0.1385610963075752


## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [ ]:
#Importação de pacote
import numpy as np
#Definição das listas (hipotético)
lista_a = np.array([2.0, 3.0, 5.0])
lista_b = np.array([10, 20, 30])
lista_c = np.array([1, 2, 3])

# a)
a = [2.0, 3.0, 5.0] + [10, 20, 30]
print(a)
# b)
b = lista_a * 2
print(b)
# c)
c = lista_a + lista_b
print(c)
# d)
d = lista_a / (lista_b * lista_c)
print(d)


[2.0, 3.0, 5.0, 10, 20, 30]
[ 4.  6. 10.]
[12. 23. 35.]
[0.2        0.075      0.05555556]


## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [ ]:
#Importação de pacote:
import math
#Exercício 01
a = 2.6
b = 2.8
c = 34.7286
d = 0.0693
e = 0.1386
#lista1
lista1 = [a, b, c, d, e]
print(lista1)
#lista raiz quadrada
lista2 = [math.sqrt(x) for x in lista1] #math.sqrt() (raiz quadrada)
print(lista2)
#lista concatenação
lista3 = lista1 + lista2 #+ em listas (concatenação)
print(lista3)

[2.6, 2.8, 34.7286, 0.0693, 0.1386]
[1.61245154965971, 1.6733200530681511, 5.89309765742941, 0.26324893162176366, 0.3722902093797257]
[2.6, 2.8, 34.7286, 0.0693, 0.1386, 1.61245154965971, 1.6733200530681511, 5.89309765742941, 0.26324893162176366, 0.3722902093797257]


## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [6]:
#Importação pacote:
import numpy as np

#lista3:
lista3 = [2.6, 2.8, 34.7286, 0.0693, 0.1386, 
          1.61245154965971, 1.6733200530681511, 
          5.89309765742941, 0.26324893162176366, 
          0.3722902093797257]

#Duplicação
lista_duplicada = lista3 * 2 

#Numpy array
array = np.array(lista_duplicada)

#Reshape para 5 linhas e 4 colunas
array_reshape = array.reshape(5, 4)
print(array_reshape)

[[ 2.6         2.8        34.7286      0.0693    ]
 [ 0.1386      1.61245155  1.67332005  5.89309766]
 [ 0.26324893  0.37229021  2.6         2.8       ]
 [34.7286      0.0693      0.1386      1.61245155]
 [ 1.67332005  5.89309766  0.26324893  0.37229021]]


## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [7]:
#Médias:
medias = array_reshape.mean(axis=0)
lista_medias = list(medias)
print(lista_medias)

[np.float64(7.8807537969379835), np.float64(2.149427883293769), np.float64(7.8807537969379835), np.float64(2.149427883293769)]


## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [13]:
import numpy as np

# array do exercício 4 (exemplo)
array_reshape = np.array([
    [ 2.6,         2.8,        34.7286,      0.0693],
    [ 0.1386,      1.61245155,  1.67332005,  5.89309766],
    [ 0.26324893,  0.37229021,  2.6,         2.8],
    [34.7286,      0.0693,      0.1386,      1.61245155],
    [ 1.67332005,  5.89309766,  0.26324893,  0.37229021]
])
#Numero de elementos:
num_elementos = array_reshape.shape[0] * array_reshape.shape[1]
print("Número de elementos:", num_elementos)
#Média
medias = array_reshape.mean(axis=0)
novo_array = np.vstack([array_reshape, medias])
print(novo_array)

Número de elementos: 20
[[ 2.6         2.8        34.7286      0.0693    ]
 [ 0.1386      1.61245155  1.67332005  5.89309766]
 [ 0.26324893  0.37229021  2.6         2.8       ]
 [34.7286      0.0693      0.1386      1.61245155]
 [ 1.67332005  5.89309766  0.26324893  0.37229021]
 [ 7.8807538   2.14942788  7.8807538   2.14942788]]


## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [16]:
#Importar pacotes
import numpy as np
import pandas as pd

#Arrai 06
array = np.array([
    [2.6, 2.8, 34.7286, 0.0693],
    [0.1386, 1.61245155, 1.67332005, 5.89309766],
    [0.26324893, 0.37229021, 2.6, 2.8],
    [34.7286, 0.0693, 0.1386, 1.61245155],
    [1.67332005, 5.89309766, 0.26324893, 0.37229021],
    [7.8807538,   2.14942788,  7.8807538,   2.14942788]  
])
#Reshape
array_reshape = array.reshape(-1, 4)
#DataFrame
df = pd.DataFrame(array_reshape)
#Arredondar
df = df.round(3)
print(df)

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149


## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [17]:
#Importação pacotes
import pandas as pd
import numpy as np
#DataFrame
df = pd.DataFrame([
    [2.6, 2.8, 34.7286, 0.0693],
    [0.1386, 1.612, 1.673, 5.893],
    [0.263, 0.372, 2.6, 2.8],
    [34.7286, 0.0693, 0.1386, 1.612],
    [1.673, 5.893, 0.263, 0.372],
    [7.48, 2.95, 7.88, 2.55]  # médias das colunas (exemplo)
])
#Médias das linhas
media_linhas = df.mean(axis=1)
df['media_linhas'] = media_linhas
print(df)

         0       1        2       3  media_linhas
0   2.6000  2.8000  34.7286  0.0693     10.049475
1   0.1386  1.6120   1.6730  5.8930      2.329150
2   0.2630  0.3720   2.6000  2.8000      1.508750
3  34.7286  0.0693   0.1386  1.6120      9.137125
4   1.6730  5.8930   0.2630  0.3720      2.050250
5   7.4800  2.9500   7.8800  2.5500      5.215000


## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [19]:
#Importação de pacote
import pandas as pd

desc = df.describe()
ultima_linha = desc.iloc[-1]
ultima_coluna = df.iloc[:, -1].describe()

#Comparação
comparacao = ultima_linha.equals(ultima_coluna)

print("DESCRIBE")
print(desc)
print("Última linha do describe")
print(ultima_linha)
print("Última coluna (describe)")
print(ultima_coluna)
print("São iguais?")
print(comparacao)

DESCRIBE
               0         1          2         3  media_linhas
count   6.000000  6.000000   6.000000  6.000000      6.000000
mean    7.813867  2.282717   7.880533  2.216050      5.048292
std    13.456109  2.132928  13.455115  2.114068      3.759482
min     0.138600  0.069300   0.138600  0.069300      1.508750
25%     0.615500  0.682000   0.615500  0.682000      2.119975
50%     2.136500  2.206000   2.136500  2.081000      3.772075
75%     6.260000  2.912500   6.560000  2.737500      8.156594
max    34.728600  5.893000  34.728600  5.893000     10.049475
Última linha do describe
0               34.728600
1                5.893000
2               34.728600
3                5.893000
media_linhas    10.049475
Name: max, dtype: float64
Última coluna (describe)
count     6.000000
mean      5.048292
std       3.759482
min       1.508750
25%       2.119975
50%       3.772075
75%       8.156594
max      10.049475
Name: media_linhas, dtype: float64
São iguais?
False


## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [20]:
#Importação dos pacotes
import pandas as pd
#Renomear colunas
df.columns = [
    'coluna_1',
    'coluna_2',
    'coluna_3',
    'coluna_4',
    'media_linhas'
]
#Renomear index
df.index = [
    'linha_1',
    'linha_2',
    'linha_3',
    'linha_4',
    'linha_5',
    'medias_colunas'
]
#Médias
media_das_medias = df['media_linhas'].mean()
print("DATAFRAME FINAL")
print(df)

print("MÉDIA DAS MÉDIAS")
print(media_das_medias)

DATAFRAME FINAL
                coluna_1  coluna_2  coluna_3  coluna_4  media_linhas
linha_1           2.6000    2.8000   34.7286    0.0693     10.049475
linha_2           0.1386    1.6120    1.6730    5.8930      2.329150
linha_3           0.2630    0.3720    2.6000    2.8000      1.508750
linha_4          34.7286    0.0693    0.1386    1.6120      9.137125
linha_5           1.6730    5.8930    0.2630    0.3720      2.050250
medias_colunas    7.4800    2.9500    7.8800    2.5500      5.215000
MÉDIA DAS MÉDIAS
5.048291666666666
