# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [2]:
#A:
A = 2.0 + 3.0/5.0 ==10
print(A)
#B:
B = (A+10.2) - 5.0*2.0 <= 2.9
print(B)
#C:
C = 10 <= A/B +33.8 <100
print(C)
#D
D = 5 != A/(B+C)
print(D)
#E
E = 33 == D*2
print(E)

False
True
True
True
False


## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [14]:
a= ('a',1,True,'b',0,False) == ('a',True,1,'b',False,0)
print(a)
b = ['a',1,True,'b',0,False] == ('a',True,1,'b',False,0)
print(b)
c = ['a',1,True,'b',0,False] == ['a',True,1,'b',False,0]
print(c)
d = ['a',1,True,'b',0,False] != ['a',True,1]
print(d)
e = ['a',1,True,'b',0,False] != 1
print(e)
f = ['a',True,1] == ['a',True,1] != ['a',1,True,'b',0,False]
print(f)

True
False
True
True
True
True


## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [1]:
#Recuperação exercicio 10:
#Importando os dados
import pandas as pd  #carregando pacote
import os   
os.listdir()   #acessando local
DataFrame = pd.read_csv('data_6.csv')  #importando dados
DataFrame.head()   #visualização 5 primeiros
#Dicionário DataFrame - dados
#Número de entradas
num_entradas = DataFrame.shape[0]   #.shape (tamanho)
print(num_entradas)
#Lista com classe das colunas
classes_colunas = list(DataFrame.dtypes)    #.dtypes (tipos)
print(classes_colunas)
#Elementos de cada classe
contagem_classes = DataFrame.dtypes.value_counts().to_dict()   #.value_counts (valores contados)
print(contagem_classes)
#Lista
colunas = [DataFrame.iloc[:,0], DataFrame.iloc[:,3], DataFrame.iloc[:, 8]]   #.iloc (localização - 1)
print(colunas)
médias = []
desvios = []
terceiro_quartil = []
#Calculando valores
for col in colunas:
    médias.append(col.mean())  #.append (adicionar) + col.mean (valor da média)
    desvios.append(col.std())  #.append (adicionar) + col.std (valor do desvio padrão)
    terceiro_quartil.append(col.quantile(0.75))  #.append (adicionar) + col.quantile (valor do quatil definido por qual parte ele vai ser 0.75, 0.25...)
#Dicionário 
resultado_dicionario = {
    'num_entradas': num_entradas,  #difinição das chaves e seu valor atribuido
    'classes_colunas': classes_colunas, 
    'contagem_classes': contagem_classes, 
    'médias': médias, 
    'desvios': desvios,
    'terceiro_quartil': terceiro_quartil
}
print(resultado_dicionario)

36634
[dtype('int64'), dtype('O'), dtype('O'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('O'), dtype('O'), dtype('int64')]
{dtype('float64'): 11, dtype('O'): 4, dtype('int64'): 3}
[0        119736
1        448094
2        206893
3        333743
4        172534
          ...  
36629    404309
36630    465875
36631    791209
36632    322627
36633    398149
Name: policyID, Length: 36634, dtype: int64, 0         498960.0
1        1322376.3
2         190724.4
3              0.0
4              0.0
           ...    
36629          0.0
36630    1297057.5
36631     173286.9
36632    1499781.6
36633     373488.3
Name: eq_site_limit, Length: 36634, dtype: float64, 0         792148.90
1        1438163.57
2         192476.78
3          86854.48
4         246144.49
            ...    
36629     155065.65
36630    1577500.79

In [ ]:
#Converter o dicionário (pegando só as listas numéricas)
df_resultado = pd.DataFrame({
    'médias': resultado_dicionario['médias'],
    'desvios': resultado_dicionario['desvios'],
    'terceiro_quartil': resultado_dicionario['terceiro_quartil']
})
print(df_resultado)
#Exportar para csv
df_resultado.to_csv('resultado_df_dici.csv')
#Ler csv - indice:
df1 = pd.read_csv('resultado_df_dici.csv', index_col='Unnamed: 0')
print(df1)
#Arredondar valores
df1 = df1.round(3)
print(df1)

         médias       desvios  terceiro_quartil
0  5.486619e+05  2.599129e+05      7.742520e+05
1  7.314780e+05  1.752300e+07      0.000000e+00
2  2.571004e+06  2.036777e+07      1.128871e+06
         médias       desvios  terceiro_quartil
0  5.486619e+05  2.599129e+05      7.742520e+05
1  7.314780e+05  1.752300e+07      0.000000e+00
2  2.571004e+06  2.036777e+07      1.128871e+06
        médias       desvios  terceiro_quartil
0   548661.937  2.599129e+05        774252.000
1   731478.007  1.752300e+07             0.000
2  2571004.097  2.036777e+07       1128871.182


## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [ ]:
#importação do pacote
import numpy as np
linhas, colunas = DataFrame.shape #lihas e colunas
array_df = np.ones((linhas, colunas), dtype=int) #.ones (preenche com 1) + dtype=int (garante inteiros)
print(array_df)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [ ]:
#Comparação DF - ARRAY
comparação_df_array = (DataFrame.values == array_df).sum() #comparação posição por posição + .sum (contagem TRUE)
print(comparação_df_array)

26569


## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [18]:
#Comparação DF - ARRAY
comparaçãoMAIORES_df_array = (DataFrame.select_dtypes(include='number') > 1).sum().sum() #comparação posição por posição + .sum (contagem TRUE)
print(comparaçãoMAIORES_df_array)

226819


## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [19]:
#Comparação DF - ARRAY
comparaçãoMENORIGUAL_df_array = (DataFrame.select_dtypes(include='number') <= 1).sum().sum() #comparação posição por posição + .sum (contagem TRUE)
print(comparaçãoMENORIGUAL_df_array)

286057


## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [24]:
#Comparação DF - ARRAY
comparaçãoINTERVALO_df_array = DataFrame.select_dtypes(include='number')
entre_0_1 = ((comparaçãoINTERVALO_df_array > 0) & (comparaçãoINTERVALO_df_array < 1)).sum().sum()
print(entre_0_1)

2


## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [ ]:
linhas_num = DataFrame.select_dtypes(include='number') #Seleção dos dados numéricos
medias_linhas_num = linhas_num.mean(axis=1) #medias
lista1 = list(medias_linhas_num <= 5) #maior ou igual a 5
resultado = lista1.count(True) #contagem 
print(resultado)

0


## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [31]:
colunas_num = DataFrame.select_dtypes(include='number') #Seleção dos dados numéricos
medias_colunas_num = colunas_num.mean(axis=1) #medias
lista2 = list(medias_colunas_num > 5) #maior ou igual a 5
resultado1 = lista2.count(True) #contagem 
print(resultado1)

36634
