In [ ]:
num_1 = 4
num_2 = 2
print(num_1+num_2)
print(num_1-num_2)
print(num_1%num_2)
print(num_1//num_2)
print(num_1/num_2)

6
2
0
2


In [ ]:
tupla1 = (1, 2, 3)
tupla2 = (1, 2, 3)
print(tupla1 == tupla2) #verificação geral mas numero por numero
print(tupla1 + tupla2) #concatenar
#print(tupla1 * tupla2) #não conseguimos multiplicar tuplas 

tupla1 += tupla2
display(tupla1)
display(tupla2) 
help(display)
lista_tupla1 = list(tupla1) #transformar em lista 
#lista_tupla1 += 2 #não conseguimos somar inteiro em lista
lista_tupla1 += tupla1 #conseguimos somar tupla com lista
lista_tupla1 
lista_tupla1[2] += 2 #[qual valor da tupla será somado, assim, podemos fazer a soma com numero inteiro mas com apenas com lista]
lista_tupla1


True
(1, 2, 3, 1, 2, 3)


(1, 2, 3, 1, 2, 3)

(1, 2, 3)

Help on function display in module IPython.core.display_functions:

display(*objs, include=None, exclude=None, metadata=None, transient=None, display_id=None, raw=False, clear=False, **kwargs)
    Display a Python object in all frontends.
    
    By default all representations will be computed and sent to the frontends.
    Frontends can decide which representation is used and how.
    
    In terminal IPython this will be similar to using :func:`print`, for use in richer
    frontends see Jupyter notebook examples with rich display logic.
    
    Parameters
    ----------
    *objs : object
        The Python objects to display.
    raw : bool, optional
        Are the objects to be displayed already mimetype-keyed dicts of raw display data,
        or Python objects that need to be formatted before display? [default: False]
    include : list, tuple or set, optional
        A list of format type strings (MIME types) to include in the
        format data dict. If this is set *only* 

[1, 2, 5, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
dici1 = {"a": 1, "b": 2, "c":5}
dici2 = {"a": 10, "b": 20}
#dici1 + dici2 --> não podemos somar dicionarios porque sesu valores são definidos manualmente
dici1.update(dici2) #atualiza os elementos que não tem em um dicionario no outro 
dici1

{'a': 10, 'b': 20, 'c': 5}

In [54]:
import numpy as np

In [ ]:
array = numpy.array(lista_tupla1)
print(array)
array +=2 #conseguimos somar inteiro no array por que cada valor vai ser independente 
print(array)
array *= array 
print(array)

[1 2 5 1 2 3 1 2 3 1 2 3]
[3 4 7 3 4 5 3 4 5 3 4 5]
[ 9 16 49  9 16 25  9 16 25  9 16 25]


In [ ]:
numpy.insert(arr=array, obj=2, values= 100) #definição de posição e objeto para a inserção de um valor no array e não aceita em mais de uma posição mas aceita mais de um valor
numpy.insert(arr=array, obj=2, values= (2,5)) #definição de posição e objeto para a inserção de um valor no array e não aceita em mais de uma posição mas aceita mais de um valor
lista_tupla1[2] = 100
lista_tupla1 #aqui em lista ele substitui o valor 

array([ 9, 16,  2,  5, 49,  9, 16, 25,  9, 16, 25,  9, 16, 25])

In [ ]:
array = numpy.array(lista_tupla1).reshape(6,-1) #organizar as colunas e linhas quando só em linhas ou colunas (o -1 ignora a quantidade de coluna ou de linha e leva em consideração apenas o outro valor)
array.shape
array

array([[  1,   2],
       [100,   1],
       [  2,   3],
       [  1,   2],
       [  3,   1],
       [  2,   3]])

In [ ]:
import pandas

In [51]:
df = pandas.DataFrame(array)
df

,0,1
0,1,2
1,100,1
2,2,3
3,1,2
4,3,1
5,2,3


In [ ]:
df += df #soma de df item por item
df
array_ones = np.zeros_like(df) #zerar todos os itens
array_ones[1,1] = 100  #definição de posição quem eu quero e o valor que quero
array_ones 

array([[  0,   0],
       [  0, 100],
       [  0,   0],
       [  0,   0],
       [  0,   0],
       [  0,   0]])

In [ ]:
print("Py" != "Py")
print(1 == 1)
print(2 >= 2.01)
print(5<8)
print(4 <= 5 <7)

False
True
False
True
True


In [67]:
import numpy as np
import pandas as pd

In [ ]:
print((1,2) == (1.0, 2.0)) #mesmo conteudo e classe
print((1,2) == {1.0, 2.0}) #mesmo conteudo mas classes diferentes
print((1,2) <= (1.0, 2.0)) 
print((1,2) < (1.0, 2.0)) 
print((1,2) == (1.0, 2.0)) 
print((1,2) == (1.0, 2.0)) 
print({'a': 1, 'b': 2} == {'a': 1}) #dicionario quando iguais são verdadeiro, mas quando com um elemento diferente falso para igualdade
#".values" --> volta o valor 
#".keys" --> volta as chaves
#".items" --> volta ambos

True
False
True
False
True
True
False


In [90]:
array = np.random.normal(0, 1, 10).reshape(10,-1) #distribuição normal com média, desvio padrão, com x elementos
print(array.shape)
print(array)
print(array[:2])

(10, 1)
[[ 0.74248862]
 [ 0.03242238]
 [-0.29567981]
 [ 0.10491585]
 [ 0.62661734]
 [-1.17103073]
 [-0.56628182]
 [ 0.56684484]
 [-0.43813979]
 [ 0.69734057]]
[[0.74248862]
 [0.03242238]]


In [97]:
array = np.random.normal(0, 1, 10).reshape(10,-1) 
array2 = np.random.normal(0, 1, 10).reshape(10,-1) 
array == array2 
#para setar os valores randomizados:
np.random.seed(42) #variável global
array1 = np.random.normal(0, 1, 10).reshape(10,-1) 
array3 = np.random.normal(0, 1, 10).reshape(10,-1) 
print(array1[:2])
print(array2[:2])

[[ 0.49671415]
 [-0.1382643 ]]
[[-0.60170661]
 [ 1.85227818]]


In [101]:
pd.DataFrame(array) == pd.DataFrame(array)

,0
0,True
1,True
2,True
3,True
4,True
5,True
6,True
7,True
8,True
9,True


In [104]:
df1 = pd.DataFrame(array1)
df2 = pd.DataFrame(array2)
df1.head()

,0
0,0.496714
1,-0.138264
2,0.647689
3,1.523030
4,-0.234153


In [110]:
print(1 == 1 and 1 == 1)
print(1 == 1 and 1 == 5)
print(1 == 1 and 1 == 1)
print(1 == 1 or 1 == 1)
print(1 == 1 or 1 == 5)


True
False
True
True
True


In [111]:
print(True and not True)
print(True or True)
print(False or True)
print(True and False)
print(True is False)
print(False is not True)

False
True
True
False
False
True


In [ ]:
p = 1
q = r 
r = 0
print(p == q and p == r)
print(p == q or p == r)

False
False


In [120]:
print(1 in [1, 2, 3, 4, 5]) #in funciona para o que esta dentro do que 
print(p is r)
print(r is not q)
print(q is r)
print(q is not p)

True
False
False
True
True
