In [ ]:
#Estruturas condicionais
#dentro de uma condicional --> endentação 
# : traz o resultado da condicional; se for verdade
# if = se
# else = se não 

In [ ]:
#Estrutura de repetição 
#Interação: repetição de um ou mais ações --> enquanto for verdade faça alguma coisa
#while: enquanto tiver dentro daquela condição faça, quando parar de ser, pare de fazer

In [1]:
import numpy as np
import pandas as pd

In [3]:
array = np.random.normal(20, 2.5, 40). reshape(8,5)
array

array([[20.7350449 , 20.46893412, 18.61737472, 18.69772077, 17.52270471],
       [21.18858585, 20.83765625, 21.08568919, 15.85967781, 18.96199545],
       [22.19401187, 17.78578666, 25.28446198, 16.45487705, 18.85731915],
       [18.28022739, 24.03619654, 13.0786942 , 20.54426413, 21.14868458],
       [20.59512176, 20.27393136, 23.52716212, 19.68000855, 22.18122651],
       [25.27064939, 23.05347468, 19.80893576, 19.23259015, 21.09959025],
       [23.22551628, 18.32563985, 21.65443567, 20.90691541, 23.14183792],
       [21.70741254, 18.62274427, 20.85859696, 16.34921958, 17.86092562]])

In [ ]:
if array[3,1] >= 200:
    pass #verificação
else: 
    pass

In [ ]:
if array[3,1] >= 200:
   resposta = 'O valor é maior ou igual a 200'
elif array[3,1] >10: #outra condição para ser verificada se a outra condição for falsa
    resposta = 'O valor é maior que 10'
else:
     resposta = 'O valor não é maior ou igual a 200' 
resposta

'O valor é maior que 10'

In [9]:
if np.all(array >0):
    print('Todos os valores são mais que 0')

Todos os valores são mais que 0


In [10]:
array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [ ]:
contador = 0
while contador < 10:
    contador += 1
    print(contador)

1
2
3
4
5
6
7
8
9
10


In [26]:
array3 = np.array([10, 20, 30, 40, 50])
array3

array([10, 20, 30, 40, 50])

In [24]:
contador1 = 0
while contador1 < len(array3):
    print(array3[contador1])
    contador1 += 1


10
20
30
40
50


In [29]:
for i in range(len(array3)):
    print(array3[i])

10
20
30
40
50


In [39]:
for i in enumerate(array3):
    print(i)
    print(i[1])

(0, np.int64(10))
10
(1, np.int64(20))
20
(2, np.int64(30))
30
(3, np.int64(40))
40
(4, np.int64(50))
50


In [40]:
for key, value in enumerate(array3):
    print(key, value)

0 10
1 20
2 30
3 40
4 50
